### ISSUE TITLE
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

### ISSUE THREAD

**Issue by albundy0815** [victronenergy/venus-influx-loader#9]
I tried to implement this project via docker for windows.. 
As soon as I'm on part https://github.com/victronenergy/venus-influx-loader#run-venus-influx-loader-docker-image-locally
I'm getting the error message in the header. Any advice to solve it?
![image](https://github.com/victronenergy/venus-influx-loader/assets/97403164/1ea8bb1a-274f-4931-ab21-45a77149882d)

**Comment by mman** [comment]
Hi @albundy0815 

I believe this is a side effect of us using `docker run --interactive` and well known issue of Git's `bash` port for Windows. Please see the FAQ here for detailed explanation: https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it.

However, since none of our scripts actually requires docker to be interactive (to accept input) I have fixed it by dropping the `-it` from `docker run`.

Please `git pull`, try again and let me know so that we can close the issue.
Martin

**Comment by albundy0815** [comment]
Hi @mman ,

I tried it again via pull. InfluxDB is created (but bash "hangs" and when I close it, the influxDB image will be shut downed. So I've created a second bash and this "hangs" on the "last" command:
![image](https://github.com/victronenergy/venus-influx-loader/assets/97403164/b9f742eb-9f6d-40c4-87ec-79b106ce4a84)


Any additional hints how to solve it?

**Comment by mman** [comment]
@albundy0815 When you start influx in one of the `bash` windows you need to keep it open, because closing it will terminate the Influx. This is expected and consider this being for debugging purposes only. If you want to run this in daily production it's better to then create a full `docker compose` setup that you can spin up and run in the background.

I'm confused where the  `': No such file or directory` error comes from but I have an idea. (Note: I do not have a windows box to test, and I can not run docker inside of a virtual machine, so I am just guessing here)

Please replace the first two lines in `run-dev-image.sh` wit the following lines:

```
#!/bin/bash
set -x

```

This will change the shell to be used to `/bin/bash` and will print every command invoked in detail (via `set -x`) and then send me please the output...

**Comment by albundy0815** [comment]
Hi @mman:
I've adjusted the run-dev-image.sh and result is :-(

xxx MINGW64 /c/Users
$ cd ..

xxx MINGW64 /c
$ cd tmp

xxx MINGW64 /c/tmp
$ cd venus-influx-loader/

xxx MINGW64 /c/tmp/venus-influx-loader (master)
$ export OWNER="martin"

xxx MINGW64 /c/tmp/venus-influx-loader (master)
$ (cd docker && ./run-dev-image.sh)
+ VER=develop
+ OWNER=martin
+ TARGET=venus-influx-loader
+ TAG=martin/venus-influx-loader:develop
+ NETWORK=vil
+ VIL_INFLUXDB_URL=http://host.docker.internal:8086
+ VIL_INFLUXDB_USERNAME=s3cr4t
+ VIL_INFLUXDB_PASSWORD=s3cr4t
+ docker network inspect vil
+ docker run -p 8088:8088 --network vil -e VIL_INFLUXDB_URL=http://host.docker.internal:8086 -e VIL_INFLUXDB_USERNAME=s3cr4t -e VIL_INFLUXDB_PASSWORD=s3cr4t -v /c/tmp/venus-influx-loader/docker/../config:/config martin/venus-influx-loader:develop
': No such file or directory

xxx MINGW64 /c/tmp/venus-influx-loader (master)
$

**Comment by mman** [comment]
@albundy0815 Thanks for doing the tests... This is some windows weirdness in how it interprets the command line. The "No such file or directory" error message could point towards the `-v` argument that mounts the local `config` directory into the docker.

Could you try to copy paste the following commands? I have added additional shell quotes.

```
cd docker

ls -ld ../config

docker run -p "8088:8088" --network vil -e VIL_INFLUXDB_URL="http://host.docker.internal:8086/" -e VIL_INFLUXDB_USERNAME="s3cr4t" -e VIL_INFLUXDB_PASSWORD="s3cr4t" -v "/c/tmp/venus-influx-loader/docker/../config:/config" "martin/venus-influx-loader:develop"
```

**Comment by albundy0815** [comment]
@mman: thanks for the new commands. My "problem" is, that I'm not a developer and I'm struggling a lot. Hopefully within the final solution, I'm able to safe the values in a "own" influxDB version 2 (due to the 4 GB issue). 

Result is:

xxx MINGW64 /c/tmp/venus-influx-loader (master)
$ cd docker

xxx MINGW64 /c/tmp/venus-influx-loader/docker (master)
$ ls -ld ../config
drwxr-xr-x 1 David 197121 0 Nov 15 14:48 ../config/

xxx MINGW64 /c/tmp/venus-influx-loader/docker (master)
$ docker run -p "8088:8088" --network vil -e VIL_INFLUXDB_URL="http://host.docker.internal:8086/" -e VIL_INFLUXDB_USERNAME="s3cr4t" -e VIL_INFLUXDB_PASSWORD="s3cr4t" -v "/c/tmp/venus-influx-loader/docker/../config:/config" "martin/venus-influx-loader:develop"
': No such file or directory

xxx MINGW64 /c/tmp/venus-influx-loader/docker (master)
$

**Comment by mman** [comment]
@albundy0815 Sorry for not responding earlier. I need to get my hands on a physical Windows machine where I can try the steps you are doing, since I only have virtualised Windows that can not run docker for now... please stay tuned...

**Comment by mman** [comment]
Sorry @albundy0815 it took me so long, needed to find a working Windows machine. But now I was able to track everything down and if you `git reset --hard HEAD && git pull` both repositories and try again from scratch it should work just fine.

I have verified that building and running the local dev images and influxdb works and you can experiment.

Please ping me if you need help.
